#!/bin/bash

# Load our library functions
SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "${SCRIPT_DIR}/lib.sh"

build() {
  if [ -n "$GOPATH" ]; then
    echo "Building stack!"

    STACKBUILD=${1:-${GOPATH}/bin/stack}

    get_commit
    get_version

    LDFLAGS="-X github.com/gophercloud/gophercloud/cli/version.Commit=${COMMIT} \
             -X github.com/gophercloud/gophercloud/cli/version.Version=${VERSION}"
    CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags "${LDFLAGS}" -o "${STACKBUILD}"
    return $?
  else
    echo "\$GOPATH must be defined. Do you have go setup?"
    return 1
  fi
}

build "$1"
